version: "3"

services:
  node:  
    build: 
      context: .
      dockerfile: node.Dockerfile
    command: npm run server
    ports:
    - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_ADDRESS=mongodb
    networks:
      - nodeapi
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:  
    image: mongo
    networks:
      - nodeapi

networks:
  nodeapi:
    driver: bridge