version: "3"

services:
  node:  
    build: 
      context: .
      dockerfile: dev.Dockerfile
    command: npm run server
    ports:
    - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_ADDRESS=mongodb
    networks:
      - nodeapi

  mongodb:  
    image: mongo
    networks:
      - nodeapi

networks:
  nodeapi:
    driver: bridge